---
- name: include vars
  include_vars: roles/users/base_local/vars/user_list.yml

- name: add a new group
  group: name='{{item.name}}' gid='{{item.id}}'
  with_items:
    - '{{users}}'

- name: add a new user
  user: name='{{item.name}}' state=present generate_ssh_key=no groups='{{item.group}}' group='{{item.name}}' uid='{{item.id}}' password='{{item.passwd}}'
  register: adduser_result
  with_items:
    - '{{users}}'

- name: mk .ssh
  file: path={{item.home}}/.ssh mode=700 group='{{item.name}}' owner='{{item.name}}' state=directory
  with_items: '{{adduser_result.results}}'
  when: item.changed == True

- name: check existance authorized_keys
  stat: path=/home/{{item.name}}/.ssh/authorized_keys
  register: authorized_keys
  with_items: 
    - '{{users}}'

- name: cp authorized_key
  copy: src=roles/users/tmp/tmp_authorized_keys/'{{item.name}}'.pub dest='{{item.home}}'/.ssh/authorized_keys mode=600 group='{{item.name}}' owner='{{item.name}}'
  with_items: '{{adduser_result.results}}'
  when: 
    - item.changed == True
    - not authorized_keys.stat.exists
